=== younghoonNa/SQL/XML/week8/books.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT book_list (book+)>
<!ELEMENT book (title, page, (publisher)?)>

<!ELEMENT title (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>

<!ATTLIST book author CDATA #REQUIRED>
<!ATTLIST book price CDATA #IMPLIED>

=== younghoonNa/SQL/XML/week8/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book_list SYSTEM "books.dtd">


<book_list>
	<book price = "16500" author = "유현준">
		<title>공간이 만든 공간</title>
		<page>408</page>
		<publisher>을유문화사</publisher>
	</book>
	
	<book  price = "22000" author = "강붕">
		<title>혼군, 명군, 폭군</title>
		<page>519</page>
		<publisher>왕의서재</publisher>
	</book>
	
	<book  price = "12500" author = "한노 라우테르베르크">
		<title>나는 건축가다</title>
		<page>276</page>
		<publisher>현암사</publisher>
	</book>
	
	<book  price = "16000" author = "서현">
		<title>건축, 음악처럼 듣고 미술처럼 보다</title>
		<page>334</page>
		<publisher>효형출판</publisher>
	</book>
	
	<book  price = "15000" author = "앨빈 토플러">
		<title>제 3의 물결</title>
		<page>492</page>
		<publisher>범우사</publisher>
	</book>
</book_list>
